const fs=require('fs'),assert=require('assert/strict'),{createRequire}=require('module');
const root=require('path').resolve(__dirname,'..');const req=createRequire(fs.realpathSync(root+'/node_modules/wrangler/package.json'));const {Miniflare}=req('miniflare');
(async()=>{const mf=new Miniflare({modulesRoot:root+'/dist/server',modules:['index.js',...fs.readdirSync(root+'/dist/server',{recursive:true}).filter(p=>/\.m?js$/.test(p)&&p!=='index.js')].map(p=>({type:'ESModule',path:root+'/dist/server/'+p})),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['DISC_PHOTOS']});try{const db=await mf.getD1Database('DB');for(const file of fs.readdirSync(root+'/drizzle').filter(f=>f.endsWith('.sql')).sort())for(const sql of fs.readFileSync(root+'/drizzle/'+file,'utf8').split('--> statement-breakpoint'))if(sql.trim())await db.prepare(sql.trim()).run();
const call=async(path,method='GET',body,user='a',origin='http://atlas.test')=>{const headers={};if(user){headers['oai-authenticated-user-id']='test-'+user;headers['oai-authenticated-user-email']=user+'@example.test';}if(method!=='GET'){headers['content-type']='application/json';headers.origin=origin;}const r=await mf.dispatchFetch('http://atlas.test/api/'+path,{method,headers,...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()}};
assert.equal((await call('profile','PUT',{},null)).status,401);assert.equal((await call('profile','PUT',{},'a','https://other.test')).status,403);
const p={level:'intermediate',style:'forehand',hand:'right',goal:'control',course:'mixed',speedUnit:'mph',distance:330,releaseSpeed:null,rpm:null};assert.equal((await call('profile','PUT',p)).status,200);assert.equal((await call('account')).data.profile.rpm,null);assert.equal((await call('account','GET',null,'b')).data.profile,null);
assert.equal((await call('profile','PUT',{...p,rpm:9000})).status,400);
const c=JSON.parse(fs.readFileSync(root+'/public/data.json')).discs,d=c.find(d=>d.name==='Destroyer');const item={discId:d.id,plastic:'Star',weight:173,wear:'seasoned',notes:'Test disc'};
const added=await call('bag','POST',item);assert.equal(added.status,200);assert.equal(added.data.bag.length,1);const id=added.data.bag[0].id;
assert.equal((await call('account','GET',null,'b')).data.bag.length,0);await call('bag','DELETE',{id},'b');assert.equal((await call('account')).data.bag.length,1);
assert.equal((await call('bag','POST',{...item,discId:'invented'})).status,400);assert.equal((await call('coach','POST',{messages:[{role:'user',content:'Help with my bag'}]})).data.code,'coach_not_configured');await call('bag','DELETE',{id});assert.equal((await call('account')).data.bag.length,0);
const photo='data:image/jpeg;base64,'+fs.readFileSync(root+'/tests/fixtures/disc-photo.jpg').toString('base64');
const withPhoto=await call('bag','POST',{...item,color:'Blue',photo});assert.equal(withPhoto.status,200);const saved=withPhoto.data.bag[0];assert.equal(saved.color,'Blue');assert.ok(saved.photoUrl);assert.equal(saved.photoKey,undefined);
const readPhoto=async(user)=>mf.dispatchFetch('http://atlas.test'+saved.photoUrl,{headers:user?{'oai-authenticated-user-id':'test-'+user,'oai-authenticated-user-email':user+'@example.test'}:{}});
assert.equal((await readPhoto('a')).status,200);assert.equal((await readPhoto('b')).status,404);assert.equal((await readPhoto(null)).status,401);
assert.equal((await call('bag','PUT',{...item,id:saved.id,color:'Pink'},'b')).status,404);
const edited=await call('bag','PUT',{...item,id:saved.id,color:'Pink'});assert.equal(edited.data.bag[0].color,'Pink');assert.ok(edited.data.bag[0].photoUrl);
assert.equal((await call('bag','POST',{...item,photo:'data:image/svg+xml;base64,PHN2Zz4='})).status,400);
const bucket=await mf.getR2Bucket('DISC_PHOTOS');assert.equal((await bucket.list()).objects.length,1);
const replaced=await call('bag','PUT',{...item,id:saved.id,photo});assert.equal(replaced.status,200);assert.notEqual(replaced.data.bag[0].photoUrl,saved.photoUrl);assert.equal((await bucket.list()).objects.length,1);
const removed=await call('bag','PUT',{...item,id:saved.id,removePhoto:true});assert.equal(removed.data.bag[0].photoUrl,null);assert.equal((await bucket.list()).objects.length,0);
await call('bag','PUT',{...item,id:saved.id,photo});await call('bag','DELETE',{id:saved.id});assert.equal((await bucket.list()).objects.length,0);
// Data export/deletion must be private and must remove referenced photo objects.
await call('profile','PUT',p);await call('bag','POST',{...item,photo});
await call('profile','PUT',{...p,distance:200},'b');await call('bag','POST',{...item,photo},'b');
await db.prepare('INSERT INTO coach_usage(user_id,day,count) VALUES (?,?,?)').bind('test-a','2026-09-24',2).run();
assert.equal((await call('data','GET',null,null)).status,401);
const exportA=await call('data');assert.equal(exportA.data.profile.distance,330);assert.equal(exportA.data.bag.length,1);assert.equal(exportA.data.coachUsage[0].count,2);
assert.equal((await call('data','GET',null,'b')).data.profile.distance,200);
assert.equal((await call('data','DELETE',{confirmation:'wrong'})).status,400);
assert.equal((await call('data','DELETE',{confirmation:'DELETE MY DATA'},'a','https://other.test')).status,403);
assert.equal((await call('data','DELETE',{confirmation:'DELETE MY DATA'})).status,200);
assert.equal((await call('account')).data.profile,null);assert.equal((await call('account')).data.bag.length,0);assert.equal((await call('data')).data.coachUsage.length,0);
assert.equal((await call('account','GET',null,'b')).data.bag.length,1);assert.equal((await bucket.list()).objects.length,1);
assert.equal((await call('data','DELETE',{confirmation:'DELETE MY DATA'})).status,200);
console.log('PASS: data export, confirmed deletion, photo cleanup, repeat deletion, and second-account isolation.');
const cigarra=c.find(d=>d.catalogName==='Cigarra');assert.equal(cigarra.speed,7);assert.equal(cigarra.production.status,'catalog_listed');
console.log('PASS: private photo upload/read/replace/remove/delete, color and edit persistence, Cigarra mapping; real Worker/D1 profile persistence, nullable measurements, bag save/load/delete, user isolation, anonymous rejection, cross-origin rejection, validation, and honest unconfigured coach response.');
}finally{await mf.dispose()}})().catch(e=>{console.error(e);process.exitCode=1});
